Checking for existence of the Bash-it script first
Also moved to a heredoc for generating content in the output file.

diff --git a/home/bin/backup-bash-it b/home/bin/backup-bash-it
--- a/home/bin/backup-bash-it
+++ b/home/bin/backup-bash-it
@@ -1,5 +1,21 @@
 #!/usr/bin/env bash
 
+# Find out where Bash-it is located, with a reasonable fallback
+__BASH_IT_INSTALL=${BASH_IT:-$HOME/.bash_it}
+
+if [ ! -f "$__BASH_IT_INSTALL/bash_it.sh" ] ; then
+  echo "Bash-it not found at $__BASH_IT_INSTALL."
+  # shellcheck disable=SC2016
+  echo 'Please set the $BASH_IT variable to point to your Bash-it installation.'
+  exit 1
+else
+  echo "Bash-it location  : $__BASH_IT_INSTALL"
+fi
+
+# Bash-it needs to be sourced in order to call "bash-it show" in the script.
+# shellcheck disable=SC1090
+source "$__BASH_IT_INSTALL/bash_it.sh"
+
 # Allow the user to provide a context name, e.g. 'home' or 'work'.
 # If no context is provided, use 'default'.
 BACKUP_FILE_NAME_CONTEXT=${1:-default}
@@ -7,15 +23,6 @@ BACKUP_FILE_NAME_CONTEXT=${1:-default}
 BACKUP_FILE_NAME="$HOME/.homesick/repos/dotfiles/bash_it_config_$BACKUP_FILE_NAME_CONTEXT.sh"
 
 echo "Backing up to file: $BACKUP_FILE_NAME"
-
-# Find out where Bash-it is located, with a reasonable fallback
-__BASH_IT_INSTALL=${BASH_IT:-$HOME/.bash_it}
-
-echo "Bash-it location  : $__BASH_IT_INSTALL"
-
-# Bash-it needs to be sourced in order to call "bash-it show" in the script.
-# shellcheck disable=SC1090
-source "$__BASH_IT_INSTALL/bash_it.sh"
 
 # Reusable function that does the "bash-it show" parsing and prints the results
 # in the desired format.
@@ -43,22 +50,19 @@ echo "#!/usr/bin/env bash" > "$BACKUP_FILE_NAME"
 
 # Print the desired output to the created file
 {
-  echo ""
+  cat <<'CONTENT_END'
 
-  echo '# Find out where Bash-it is located, with a reasonable fallback'
-  # shellcheck disable=SC2016
-  echo '__BASH_IT_INSTALL=${BASH_IT:-$HOME/.bash_it}'
-  # shellcheck disable=SC2016
-  echo 'echo "Bash-it location: $__BASH_IT_INSTALL"'
-  echo ""
+# Find out where Bash-it is located, with a reasonable fallback
+__BASH_IT_INSTALL=${BASH_IT:-$HOME/.bash_it}
+echo "Bash-it location: $__BASH_IT_INSTALL"
 
-  echo "# shellcheck disable=SC1090"
-  # shellcheck disable=SC2016
-  echo 'source "$__BASH_IT_INSTALL/bash_it.sh"'
-  echo ""
-  echo "bash-it disable alias      all"
-  echo "bash-it disable completion all"
-  echo "bash-it disable plugin     all"
+# shellcheck disable=SC1090
+source "$__BASH_IT_INSTALL/bash_it.sh"
+
+bash-it disable alias      all
+bash-it disable completion all
+bash-it disable plugin     all
+CONTENT_END
 
   build-enable-array "alias"
   build-enable-array "completion"
